import type { Metadata } from "next";
import { Edu_QLD_Beginner } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const eduQLD = Edu_QLD_Beginner({
  subsets: ["latin"],
  weight: "700", // Available weights
  variable: "--font-edu-qld", // Optional: CSS variable
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${eduQLD.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
